import type { Card } from "@/types/card";

export const SEED_CARDS: Card[] = [
  {
    id: "seed-webhook",
    categorie: "RÉSEAU",
    titre: "Webhook",
    tldr: "Un webhook est une notification HTTP qu'une application envoie automatiquement à une autre dès qu'un événement précis se produit, sans que personne n'ait à interroger le système en boucle.",
    analogie: "Comme une sonnette : au lieu de vérifier ta porte toutes les 5 minutes, on te prévient exactement quand quelqu'un arrive.",
    cas_usage: "Notifier ton serveur en temps réel à chaque paiement Stripe reçu.",
    schema: ["Un événement se produit (paiement)", "Stripe appelle ton URL", "Ton serveur reçoit les données", "Tu déclenches une action"],
  },
  {
    id: "seed-ssh",
    categorie: "SÉCURITÉ",
    titre: "SSH",
    signification: "SSH = Secure Shell",
    tldr: "SSH est un protocole qui chiffre la connexion entre ton terminal et un serveur distant, te permettant de l'administrer à distance sans que personne ne puisse intercepter tes commandes.",
    analogie: "Un tunnel privé et verrouillé entre ton clavier et une machine à l'autre bout du monde.",
    cas_usage: "Se connecter à un serveur distant pour y déployer une nouvelle version d'une application.",
    schema: ["Tu lances ssh user@ip", "Négociation chiffrée", "Authentification vérifiée", "Session sécurisée ouverte"],
  },
  {
    id: "seed-vps",
    categorie: "SYSTÈME",
    titre: "VPS",
    signification: "VPS = Virtual Private Server",
    tldr: "Un VPS est une portion isolée d'un serveur physique, avec ses propres ressources dédiées, qui se comporte comme une machine indépendante alors qu'elle en partage une avec d'autres.",
    analogie: "Comme un appartement dans un immeuble : ton propre espace fermé à clé, même si le bâtiment est partagé.",
    cas_usage: "Héberger une application web à petit budget sans serveur physique complet.",
    schema: ["Un serveur physique existe", "Il est découpé en tranches", "Chaque VPS est isolé", "Tu gères le tien en autonomie"],
  },
  {
    id: "seed-nosql",
    categorie: "DONNÉES",
    titre: "NoSQL",
    tldr: "Une base NoSQL stocke des données sans schéma de tables rigide, souvent sous forme de documents JSON flexibles, ce qui facilite l'évolution rapide de la structure des données.",
    analogie: "Un classeur où chaque fiche peut avoir des champs différents, contrairement à un tableau Excel figé.",
    cas_usage: "Stocker des profils utilisateurs dont les champs varient beaucoup d'un compte à l'autre.",
    schema: ["Un document JSON est créé", "Stocké sans schéma fixe", "Interrogé par requête", "Structure libre à tout moment"],
  },
  {
    id: "seed-dns",
    categorie: "RÉSEAU",
    titre: "DNS",
    signification: "DNS = Domain Name System",
    tldr: "Le DNS traduit un nom de domaine lisible par un humain en adresse IP compréhensible par les machines, l'étape invisible avant chaque connexion à un site.",
    analogie: "Un carnet d'adresses géant qui transforme un nom de restaurant en son adresse postale exacte.",
    cas_usage: "Faire pointer un nom de domaine acheté vers le serveur qui héberge ton site.",
    schema: ["Tu tapes eduki.app", "Requête envoyée au DNS", "Le DNS renvoie l'adresse IP", "Connexion au bon serveur"],
  },
  {
    id: "seed-cache",
    categorie: "SYSTÈME",
    titre: "Cache",
    tldr: "Le cache garde une copie temporaire et rapide d'accès d'une donnée coûteuse à recalculer, pour éviter de refaire le même travail lourd à chaque demande.",
    analogie: "Garder les épices utilisées souvent sur le plan de travail plutôt que rangées au fond du placard.",
    cas_usage: "Éviter de recalculer un résultat identique à chaque requête sur une page très visitée.",
    schema: ["Une requête arrive", "Donnée déjà en cache ?", "Oui → réponse instantanée", "Non → calcul puis mise en cache"],
  },
  {
    id: "seed-orm",
    categorie: "DONNÉES",
    titre: "ORM",
    signification: "ORM = Object-Relational Mapping",
    tldr: "Un ORM permet de manipuler une base de données via des objets de ton langage plutôt qu'en écrivant du SQL brut, rendant le code plus lisible et portable.",
    analogie: "Un traducteur qui te permet de parler ta langue pendant qu'il gère la conversation avec la base de données.",
    cas_usage: "Créer et récupérer des enregistrements sans écrire de requêtes SQL manuellement.",
    schema: ["Tu écris User.find(42)", "L'ORM traduit en SQL", "La base répond en lignes", "L'ORM renvoie un objet"],
  },
  {
    id: "seed-jwt",
    categorie: "SÉCURITÉ",
    titre: "JWT",
    signification: "JWT = JSON Web Token",
    tldr: "Un JWT est un jeton signé qui prouve l'identité d'un utilisateur entre deux requêtes, sans que le serveur ait besoin de retenir une session en mémoire.",
    analogie: "Un bracelet de festival scellé : vérifiable comme authentique sans rappeler l'organisateur à chaque fois.",
    cas_usage: "Authentifier les requêtes d'un utilisateur connecté sur une API sans session serveur.",
    schema: ["Connexion réussie", "Serveur signe un jeton", "Jeton envoyé à chaque requête", "Serveur vérifie la signature"],
  },
  {
    id: "seed-docker",
    categorie: "SYSTÈME",
    titre: "Conteneur",
    tldr: "Un conteneur empaquette une application avec toutes ses dépendances dans un environnement isolé et portable, garantissant qu'elle tourne identiquement partout.",
    analogie: "Une boîte de déménagement standardisée : peu importe le camion, tout est déjà dedans.",
    cas_usage: "Faire tourner la même application en développement local et en production sans surprise.",
    schema: ["L'app + ses dépendances", "Empaquetées dans une image", "Lancées comme conteneur", "Identique sur toute machine"],
  },
  {
    id: "seed-loadbalancer",
    categorie: "RÉSEAU",
    titre: "Load Balancer",
    tldr: "Un load balancer répartit le trafic entrant entre plusieurs serveurs identiques pour qu'aucun ne soit surchargé, améliorant performance et résilience.",
    analogie: "Un maître d'hôtel qui répartit les clients entre plusieurs caisses plutôt que tous vers la même.",
    cas_usage: "Répartir des milliers de requêtes simultanées entre plusieurs serveurs backend.",
    schema: ["Requêtes entrantes massives", "Load balancer les reçoit", "Réparties entre serveurs", "Aucun serveur surchargé"],
  },
  {
    id: "seed-designpattern",
    categorie: "ARCHITECTURE",
    titre: "Design Pattern",
    tldr: "Un design pattern est une solution éprouvée et réutilisable à un problème de conception logicielle récurrent, un vocabulaire commun entre développeurs.",
    analogie: "Un plan d'architecte standard pour construire un escalier : la logique est connue, les matériaux changent.",
    cas_usage: "Utiliser le pattern Singleton pour garantir une seule connexion active à la base de données.",
    schema: ["Problème récurrent identifié", "Pattern connu choisi", "Structure appliquée au code", "Réutilisable ailleurs"],
  },
  {
    id: "seed-pwa",
    categorie: "ARCHITECTURE",
    titre: "PWA",
    signification: "PWA = Progressive Web App",
    tldr: "Une PWA est un site web qui se comporte comme une application native : installable sur l'écran d'accueil, capable de fonctionner hors ligne.",
    analogie: "Un site web qui a appris à se faire passer pour une vraie application, sans passer par un store.",
    cas_usage: "Permettre à un utilisateur d'installer ton app depuis le navigateur, sans App Store ni Play Store.",
    schema: ["Un site web classique", "Un manifest.json ajouté", "Un service worker actif", "Installable comme une app"],
  },
  {
    id: "seed-pointeur",
    categorie: "LANGAGE",
    titre: "Pointeur",
    tldr: "Un pointeur est une variable qui stocke l'adresse mémoire d'une autre donnée plutôt que la donnée elle-même.",
    analogie: "Une adresse postale : elle ne contient pas la maison elle-même, juste l'indication pour la trouver.",
    cas_usage: "Manipuler de grandes structures de données en C sans les copier intégralement.",
    schema: ["Variable x = 42 en mémoire", "Pointeur p stocke l'adresse", "*p accède à la valeur", "Modification indirecte possible"],
  },
  {
    id: "seed-compile",
    categorie: "LANGAGE",
    titre: "Langage compilé",
    tldr: "Un langage compilé transforme tout le code source en langage machine avant l'exécution, généralement plus rapide qu'un langage interprété ligne par ligne.",
    analogie: "Traduire un livre entier avant de le lire, plutôt que de le traduire phrase par phrase en le lisant.",
    cas_usage: "Choisir un langage compilé comme Go ou Rust pour un service critique où la vitesse compte.",
    schema: ["Code source écrit", "Compilateur le traduit", "Exécutable en langage machine", "Exécution directe et rapide"],
  },
  {
    id: "seed-cors",
    categorie: "SÉCURITÉ",
    titre: "CORS",
    signification: "CORS = Cross-Origin Resource Sharing",
    tldr: "CORS est un mécanisme du navigateur qui contrôle si un site a le droit de faire des requêtes vers un domaine différent du sien, pour empêcher un accès non autorisé.",
    analogie: "Un videur à l'entrée qui vérifie si ton site figure sur la liste des invités autorisés du serveur.",
    cas_usage: "Autoriser explicitement ton front-end à appeler une API hébergée sur un autre domaine.",
    schema: ["Requête cross-origin envoyée", "Navigateur vérifie les headers", "Serveur autorise ou refuse", "Réponse bloquée ou acceptée"],
  },
];